name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: cd transformer && rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd transformer && cargo build --verbose
      - run: cd transformer && cargo test --verbose
  
